server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql-d.inner.ruochuchina.com:33306/ds_consumer
    username: root
    password: Ruochu123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
